version: 2.1
orbs:
  node: circleci/node@5
jobs:
  run-cypress-testcases:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Install Cypress
          command: npm install cypress
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npm run test
  deploy:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/base:stable
workflows:
  build-and-test:
    jobs:
      - run-cypress-testcases
