version: 2.1
orbs:
  node: circleci/node@5

jobs:
  run-cypress-tests:
    docker:
      - image: cypress/browsers:node14.19.1-chrome105-ff104 # Use a pre-configured Cypress image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Run Cypress Tests
          command: npm run test

workflows:
  build-and-test:
    jobs:
      - run-cypress-tests
