version: 2.1

orbs:
  node: circleci/node@5

jobs:
  run-cypress-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install --legacy-peer-deps
      - run:
          name: Install Xvfb
          command: sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Install Cypress
          command: npm install cypress --save-dev
      - run:
          name: Run Cypress Tests
          command: |
            npm run test || echo "Cypress tests failed, continuing..."
      - store_artifacts:
          path: /home/circleci/project/cypress/reports/html
          destination: cypress_report
      - run:
          name: Execution Report
          command: node index.js

workflows:
  build-and-test:
    jobs:
      - run-cypress-tests:
          filters:
            branches:
              only:
                - main   # Run this job only on the develop-circleci branch
